namespace ProcrastiN8.RulesEngine;

/// <summary>
/// Represents the result of executing a rule action.
/// </summary>
/// <remarks>
/// Action results capture the deferral instructions and excuses generated by an action.
/// </remarks>
public sealed class RuleActionResult
{
    /// <summary>
    /// Gets or sets the deferral duration recommended by this action.
    /// </summary>
    public TimeSpan DeferralDuration { get; set; } = TimeSpan.Zero;

    /// <summary>
    /// Gets or sets the excuse generated by this action.
    /// </summary>
    public string? Excuse { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the task should be blocked entirely.
    /// </summary>
    public bool ShouldBlock { get; set; }

    /// <summary>
    /// Gets or sets the blocking reason if the task should be blocked.
    /// </summary>
    public string? BlockingReason { get; set; }

    /// <summary>
    /// Gets or sets the regret multiplier to apply to future deferrals.
    /// </summary>
    public double RegretMultiplier { get; set; } = 1.0;

    /// <summary>
    /// Gets or sets a description of what the action did.
    /// </summary>
    public string ActionDescription { get; set; } = "No action taken.";
}
