name: CI & Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore ProcrastiN8.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --verbosity normal --collect:"XPlat Code Coverage"
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test/ProcrastiN8.Tests/TestResults
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v5
        with:
          files: ./test/ProcrastiN8.Tests/TestResults/**/coverage.cobertura.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  pack:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: '5.x'
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1
      - name: Restore dependencies
        run: dotnet restore ProcrastiN8.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Fetch GitHub Release Notes
        id: get_release_notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/github-script@v7
        with:
          script: |
            const tag = process.env.GITHUB_REF.split('/').pop();
            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag
            });
            core.setOutput('body', release.body || '');
      - name: Write release notes to file
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "$RELEASE_NOTES" > RELEASE_NOTES.txt
        env:
          RELEASE_NOTES: ${{ steps.get_release_notes.outputs.body || 'No release notes provided.' }}
      - name: Pack
        run: |
          VERSION_SUFFIX=""
          RELEASE_NOTES_ARG=""
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            VERSION_SUFFIX="-pr${{ github.event.pull_request.number }}.${{ github.run_number }}"
          fi
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            RELEASE_NOTES_ARG="/p:PackageReleaseNotes=\"$(cat RELEASE_NOTES.txt)\""
          fi
          dotnet pack src/ProcrastiN8/ProcrastiN8.csproj --configuration Release --no-build --output ./nupkg /p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }}$VERSION_SUFFIX $RELEASE_NOTES_ARG
      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg

  publish-gh-prerelease:
    needs: pack
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Download NuGet Package
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg
      - name: Publish pre-release to GitHub Packages (PR)
        run: dotnet nuget push ./nupkg/*.nupkg --api-key "$GH_PACKAGES_TOKEN" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

  publish-main-prerelease:
    needs: pack
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Download NuGet Package
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg
      - name: Publish pre-release to GitHub Packages (main)
        run: dotnet nuget push ./nupkg/*.nupkg --api-key "$GH_PACKAGES_TOKEN" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      - name: Publish pre-release to NuGet.org (main)
        run: dotnet nuget push ./nupkg/*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  publish-tag-release:
    needs: pack
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Download NuGet Package
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg
      - name: Publish release to GitHub Packages (tag)
        run: dotnet nuget push ./nupkg/*.nupkg --api-key "$GH_PACKAGES_TOKEN" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      - name: Publish release to NuGet.org (tag)
        run: dotnet nuget push ./nupkg/*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
